enabled_locales: ["en"]
user:
  max_name_size: 50
  max_email_size: 255
  min_password_size: 6
  avatar_profile: 200
admin:
  book:
    image_size: 50
    per_page: 20
    page_index: 1
books:
  show:
    size: 200x250
